### ISSUE TITLE
Fix regression in NumPy 1.19.0

### ISSUE THREAD

**Issue by paulmelnikow** [lace/polliwog#198]
Failing build with numpy 1.19.0:
https://app.circleci.com/pipelines/github/lace/polliwog/836/workflows/b88ac698-51bc-46ea-80b8-f9e57e7157d9/jobs/2618/steps

Passing build with numpy 1.18.4:
https://app.circleci.com/pipelines/github/lace/polliwog/793/workflows/dd32545c-872a-4547-9819-0de088c9f7b8/jobs/2535/steps

**Comment by jlevin** [comment]
We have not been able to reproduce this issue locally on MacOS.

To reproduce this issue in CI:

    Checkout [ Pin numpy < 1.19.0 to get tests passing again (#197) ](https://github.com/lace/polliwog/tree/8f12becb6fc723b15be499e3f24db7a036a7fa86)
    Update CI Docker image to cimg/python:3.7.12
    ssh into CI
    pip install numpy==1.19.0
    in python run:

import numpy as np
import vg
from polliwog import Plane

point_on_plane = np.array([1.0, 2.0, 3.0])
plane_normal = vg.normalize(np.array([3.0, 4.0, 5.0]))
plane = Plane(point_on_plane=point_on_plane, unit_normal=plane_normal)

print(plane.sign(point_on_plane))
print(plane.sign(np.array([point_on_plane])))

Both values are expected to be zero, but the last value is returned as 1.  This bug is causing the test to fail
